module.exports = {
  // Auth Action Types
  SAVE_USER: 'SAVE_USER',
  USER_LOADER: 'USER_LOADER',
  USER_LOADER_FALSE: 'USER_LOADER_FALSE',
  USER_ADDRESS: 'USER_ADDRESS',
  AREA_SEARCHED: 'AREA_SEARCHED',
  SAVE_ADD_ID: 'SAVE_ADD_ID',
  SAVE_ADD_STATE: 'SAVE_ADD_STATE',
  RESET_STATE: 'RESET_STATE',
  SAVE_ADD: 'SAVE_ADD',
  DEL_ADD: 'DEL_ADD',
  DEL_HOME_ADD: 'DEL_HOME_ADD',
  // Dashboard Action Types
  PENDING_HOME_DATA: 'PENDING_HOME_DATA',
  SUCCESS_HOME_DATA: 'SUCCESS_HOME_DATA',
  SAVE_LAT_LNG: 'SAVE_LAT_LNG',
  // Cart Actions
  ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
  EDIT_CART_ITEM: 'EDIT_CART_ITEM',
  CLEAR_CART: 'CLEAR_CART',
  DELETE_CART_ITEM: 'DELETE_CART_ITEM',
  CHANGE_ITEM_QUANTITY: 'CHANGE_ITEM_QUANTITY',
  SINGLE_COFFE_SHOP: 'SINGLE_COFFE_SHOP',
  //Combo Actions
  ADD_COMBO_TO_CART: 'ADD_COMBO_TO_CART',
  DELETE_COMBO_ITEM: 'DELETE_COMBO_ITEM',
  CHANGE_COMBO_ITEM_QUANTITY: 'CHANGE_COMBO_ITEM_QUANTITY',
  ORDER_STATUS: 'ORDER_STATUS',
  CHANGE_COUPON_STATE: 'CHANGE_COUPON_STATE',
};
